// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lykojsvzivrmoaqombqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5a29qc3Z6aXZybW9hcW9tYnF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjkwMzksImV4cCI6MjA3MzYwNTAzOX0.luBKuhMxRUSF04Y9dzFUayyg1gE2VVeCWr6OWlHQtXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});